PYTORCH_STANDARD_IMAGE_SHAPE = (3, 1024, 1024)
NUMPY_STANDARD_IMAGE_SHAPE = (1024, 1024, 3)

IDUN_OCELOT_DATA_PATH = "/cluster/projects/vc/data/mic/open/OCELOT/ocelot_data"

DEFAULT_EPOCHS = 1
DEFAULT_BATCH_SIZE = 2
DEFAULT_DATA_DIR = IDUN_OCELOT_DATA_PATH
DEFAULT_CHECKPOINT_INTERVAL = 10
DEFAULT_BACKBONE_MODEL = "resnet50"
DEFAULT_DROPOUT_RATE = 0.3
DEFAULT_LEARNING_RATE = 1e-4
DEFAULT_PRETRAINED = True
DEFAULT_WARMUP_EPOCHS = 0
